apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rest-api
spec:
  selector:
    matchLabels:
      app: user-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-rest-api
    spec:
      containers:
        - name: user-rest-api
          image: docker.mycompany.com/spring-rest-mysql:latest
          imagePullPolicy: Never
          env:
            - name: MYSQL_ADDR
              value: mysql
            - name: DATABASE_TYPE
              value: mysql
            - name: DATA_BASE_PORT
              value: "3306"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-rest-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: user-rest-api
