apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: docker.mycompany.com/postgres:latest
          imagePullPolicy: Never
          name: postgres
          env:
            - name: POSTGRES_USER
              value: spring-user
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust

          ports:
            - containerPort: 5432
              
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres

