apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: docker.mycompany.com/mysql:latest
          imagePullPolicy: Never
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: spring-user
            - name: MYSQL_PASSWORD
              value: secret
            - name: MYSQL_DATABASE
              value: test
            - name: default-authentication-plugin
              value: mysql_native_password
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql

